services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: skicommerce
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    restart: unless-stopped